import Foundation

enum Language: String, CaseIterable, Identifiable, Codable {
    case automatic = "auto", english = "en", simplified = "zh-Hans", traditional = "zh-Hant"
    var id: String { rawValue }
    var name: String { switch self { case .automatic: "自动 / Auto"; case .english: "English"; case .simplified: "简体中文"; case .traditional: "繁體中文" } }
    static var initial: Language {
        let code = Locale.preferredLanguages.first ?? "en"
        return code.hasPrefix("zh") ? (code.contains("Hant") || code.contains("TW") || code.contains("HK") ? .traditional : .simplified) : .english
    }
    func text(_ key: String) -> String {
        guard let values = Self.strings[key] else { return key }
        let resolved = self == .automatic ? Self.initial : self
        return values[resolved == .english ? 0 : resolved == .simplified ? 1 : 2]
    }
    static let strings: [String: [String]] = [
        "pasteInsertionHint": ["Paste automatically; restore the clipboard unless you copy something new.", "自动粘贴后恢复剪贴板，期间新复制的内容会保留。", "自動貼上後還原剪貼簿，期間新複製的內容會保留。"],
        "typingInsertionHint": ["Type directly without changing the clipboard.", "直接输入文字，不占用剪贴板。", "直接輸入文字，不占用剪貼簿。"],
        "copyInsertionHint": ["Copy to the clipboard, then paste manually.", "复制到剪贴板，由你手动粘贴。", "複製到剪貼簿，由你手動貼上。"],
        "resyncCredentials": ["Sync again", "重新同步", "重新同步"],
        "permissionTroubleshooting": ["Troubleshooting", "授权遇到问题？", "授權遇到問題？"],
        "settingsAccessHint": ["Open settings anytime with ⌃⌥⌘S.", "随时按 ⌃⌥⌘S 打开设置。", "隨時按 ⌃⌥⌘S 開啟設定。"],
        "basicShortHint": ["Remove fillers and repetitions; keep your wording.", "去口水词、重复，保留原话。", "去贅詞、重複，保留原話。"],
        "cleanShortHint": ["Correct grammar and lightly polish wording.", "修正语病，轻微润色。", "修正語病，輕微潤飾。"],
        "structuredShortHint": ["Organize text into paragraphs and lists as needed.", "按需分段、归类和列点。", "按需分段、歸類和列點。"],
        "privacyShort": ["Keys stay in Keychain. Audio and text go to your selected services. No text history is saved.", "密钥存于钥匙串；音频和文字由所选服务处理。不保存文字历史。", "金鑰存於鑰匙圈；音訊和文字由所選服務處理。不儲存文字歷史。"],
        "updatesShort": ["Download and install new versions manually.", "下载新版本后手动安装。", "下載新版本後手動安裝。"],
        "status": ["Status", "状态", "狀態"],
        "generalSubtitle": ["Make YouJustSay feel at home on your Mac.", "让你就说融入你的日常使用习惯。", "讓你就說融入你的日常使用習慣。"],
        "interactionSubtitle": ["Choose how you speak and where your words go.", "按你的习惯开始说话，将文字送到需要的位置。", "依你的習慣開始說話，將文字送到需要的位置。"],
        "modelConfigurationSubtitle": ["Connect speech recognition and text cleanup services.", "连接语音识别与文字整理服务。", "連接語音辨識與文字整理服務。"],
        "permissionsSubtitle": ["A little access to keep voice input working smoothly.", "管理语音输入所需的系统访问权限。", "管理語音輸入所需的系統存取權限。"],
        "aboutSubtitle": ["A quieter way to get your thoughts into words.", "让表达轻松一点。", "讓表達輕鬆一點。"],
        "visibility": ["App visibility", "应用显示", "App 顯示"],
        "startupAppearance": ["Startup & appearance", "启动与外观", "啟動與外觀"],
        "permissionHelp": ["Setup & status", "授权说明与状态", "授權說明與狀態"],
        "about": ["About", "关于", "關於"],
        "savedAutomatically": ["Changes are saved automatically", "设置自动保存", "設定自動儲存"],
        "aboutTagline": ["Speak your thoughts. Keep your voice.", "你就说，文字自然成形。", "你就說，文字自然成形。"],
        "version": ["Version", "版本", "版本"],
        "aboutDescription": ["A simple voice input app for macOS. Transcribe, optionally clean up, and insert text wherever you write.", "简洁的 macOS 语音输入工具。语音识别、可选文字整理，直接输入到你正在写作的位置。", "簡潔的 macOS 語音輸入工具。語音辨識、可選文字整理，直接輸入到你正在寫作的位置。"],
        "privacy": ["Your data", "数据与隐私", "資料與隱私"],
        "aboutPrivacy": ["Keys stay in macOS Keychain. Audio goes to the speech service; cleanup sends text to your chosen model. No text history is saved.", "密钥保存在 macOS 钥匙串。录音发送至语音服务，启用整理时文字发送至所选模型。不保存文字历史。", "金鑰保存在 macOS 鑰匙圈。錄音傳送至語音服務，啟用整理時文字傳送至所選模型。不儲存文字歷史。"],
        "updates": ["Updates", "更新", "更新"],
        "manualUpdateHint": ["This build does not support automatic updates. Install a newer release to update the app.", "当前版本尚未接入自动更新。更新时需下载并安装新版本。", "目前版本尚未接入自動更新。更新時需下載並安裝新版本。"],
        "showApplication": ["Show in Finder", "在 Finder 中显示", "在 Finder 中顯示"],
        "copyAppInfo": ["Copy app info", "复制应用信息", "複製 App 資訊"],
        "appInfoCopied": ["Copied", "已复制", "已複製"],
        "noOrganization": ["Off", "不整理", "不整理"],
        "credentialSyncFailed": ["Keys could not be saved", "密钥未能自动保存", "金鑰未能自動儲存"],
        "structured": ["Highly structured", "高度结构化", "高度結構化"],
        "basic": ["Basic cleanup", "基础整理", "基礎整理"],
        "basicHint": ["Remove meaningless fillers and stutters; adjust punctuation while keeping your wording.", "去除无意义的口水词和口吃重复，整理必要标点，尽量保留原话。", "去除無意義的贅詞和口吃重複，整理必要標點，盡量保留原話。"],
        "cleanHint": ["Clean up fillers, correct grammar and lightly polish wording while preserving your tone.", "在基础整理上修正语病、轻微调整措辞，保留原意和语气。", "在基礎整理上修正語病、輕微調整措辭，保留原意和語氣。"],
        "structuredHint": ["Clean up fillers and organize existing ideas into paragraphs, headings or lists when useful.", "在基础整理上按内容分段、归类，必要时生成标题和列表；短句不强行拆分。", "在基礎整理上按內容分段、歸類，必要時產生標題和清單；短句不強行拆分。"],
        "keychainApprovalHint": ["In the system dialog, enter your Mac login password and choose Always Allow to remember access. All keys share one Keychain item. Development updates may ask again.", "在系统弹窗输入 Mac 登录密码，选择“始终允许”可记住授权。全部密钥共用一个钥匙串条目。开发版本更新后可能需要再次确认。", "在系統彈窗輸入 Mac 登入密碼，選擇「永遠允許」可記住授權。全部金鑰共用一個鑰匙圈項目。開發版本更新後可能需要再次確認。"],
        "saveCredentials": ["Save keys", "保存密钥", "儲存金鑰"],
        "arkHint": ["Enable this model in Ark, then enter your Ark API key. Speech and Ark use separate keys.", "请在方舟开通此模型，并填写方舟 API 密钥。语音识别与方舟的密钥需分别获取。", "請在方舟開通此模型，並填寫方舟 API 金鑰。語音辨識與方舟的金鑰需分別取得。"],
        "getArkKey": ["Get an Ark API key", "前往方舟获取密钥", "前往方舟取得金鑰"],
        "arkKey": ["Ark API key", "方舟 API 密钥", "方舟 API 金鑰"],
        "speechKey": ["Speech API key", "语音 API 密钥", "語音 API 金鑰"],
        "testAPI": ["Test", "测试", "測試"],
        "testingAPI": ["Testing…", "测试中…", "測試中…"],
        "testAPISuccess": ["Test succeeded. The current configuration works.", "测试成功，当前配置可以正常调用。", "測試成功，目前設定可以正常呼叫。"],
        "testAPIFailed": ["Test failed:", "测试失败：", "測試失敗："],
        "credentialsTitle": ["Service API keys", "服务密钥", "服務金鑰"],
        "modelConfiguration": ["Model configuration", "模型配置", "模型設定"],
        "ark": ["Volcengine · Ark", "火山· 方舟", "火山· 方舟"],
        "accessibilityPurpose": ["Accessibility enables Fn shortcuts, Esc cancellation and automatic text insertion. Separate Input Monitoring permission is not required.", "辅助功能用于 Fn 快捷键、Esc 取消及自动上屏，无需另行授权输入监控。", "輔助使用用於 Fn 快速鍵、Esc 取消及自動輸入，無需另外授權輸入監控。"],
        "authorizationMismatch": ["Enabled in System Settings but still not allowed here? Repair clears this app’s old Accessibility approval and opens System Settings so you can allow it again.", "系统里已开启，这里却仍未授权？点击修复授权，清除本应用的旧辅助功能授权，再到系统设置重新允许访问。", "系統中已開啟，此處卻仍未授權？點修復授權，清除本 App 的舊輔助使用授權，再到系統設定重新允許存取。"],
        "repairAccessibility": ["Repair authorization", "修复授权", "修復授權"],
        "accessibilityRepairReady": ["Old approval cleared. Allow this app in System Settings, then return here. If it remains unavailable, quit and reopen the app.", "旧授权已清除。请在系统设置中允许本应用访问，再返回这里。若仍未生效，请退出并重新打开应用。", "舊授權已清除。請在系統設定中允許本 App 存取，再回到這裡。若仍未生效，請結束並重新開啟 App。"],
        "accessibilityRepairFailed": ["Unable to clear old approval. Open System Settings, remove the old entry and add this app from Finder, then reopen it.", "未能清除旧授权。请打开系统设置，移除旧条目，再从访达添加当前应用并重新打开。", "未能清除舊授權。請開啟系統設定，移除舊項目，再從 Finder 加入目前 App 並重新開啟。"],
        "revealApp": ["Show this app in Finder", "在访达中显示当前应用", "在 Finder 中顯示目前 App"],
        "unlockCredentials": ["Load saved keys", "读取已保存的密钥", "讀取已儲存的金鑰"],
        "keychainLocked": ["Model configuration is locked. Authorize Keychain access to edit.", "模型配置已锁定，授权访问钥匙串后才能编辑。", "模型設定已鎖定，授權存取鑰匙圈後才能編輯。"],
        "notGranted": ["Not allowed", "未授权", "未授權"],
        "notRequested": ["Not requested", "尚未授权", "尚未授權"],
        "restricted": ["Restricted by system", "系统限制", "系統限制"],
        "microphone": ["Microphone", "麦克风", "麥克風"],
        "manage": ["Manage…", "管理…", "管理…"],
        "checked": ["Checked", "已刷新", "已重新整理"],
        "listenerActive": ["Shortcut listener is active", "快捷键监听已启用", "快速鍵監聽已啟用"],
        "listenerInactive": ["Shortcut listener is not active", "快捷键监听未启用", "快速鍵監聽未啟用"],
        "restartPermission": ["Permissions are allowed but the listener could not start. Quit and reopen the app.", "权限已授权，但监听尚未启动。请退出并重新打开应用。", "權限已授權，但監聽尚未啟動。請結束並重新開啟 App。"],
        "permissionFlow": ["Allow access in System Settings, then return here. Status updates automatically; Refresh checks again.", "在系统设置中允许访问后，返回这里会自动更新状态，也可点击刷新重新检查。", "在系統設定中允許存取後，回到這裡會自動更新狀態，也可點重新整理再次檢查。"],
        "permissions": ["Permissions", "权限", "權限"],
        "provider": ["Provider", "服务商", "服務商"],
        "custom": ["Custom compatible API", "自定义兼容接口", "自訂相容介面"],
        "baseURL": ["API base URL", "API 基础地址", "API 基礎位址"],
        "customHint": ["Use an HTTPS OpenAI-compatible base URL, such as https://host/v1. The app appends /chat/completions. Your key and text go to this address.", "填写兼容 OpenAI 的 HTTPS 基础地址，如 https://host/v1。应用追加 /chat/completions。密钥与文字将发往此地址。", "填寫相容 OpenAI 的 HTTPS 基礎位址，如 https://host/v1。App 會附加 /chat/completions。金鑰與文字將傳送至此位址。"],
        "invalidEndpoint": ["Enter an HTTPS API base URL and model name.", "请填写有效的 HTTPS 基础地址和模型名称。", "請填寫有效的 HTTPS 基礎位址與模型名稱。"],
        "copyLast": ["Copy last result", "复制上次结果", "複製上次結果"],
        "copyResult": ["Copy result", "复制结果", "複製結果"],
        "insertionFailedShort": ["Insertion failed", "上屏失败", "輸入失敗"],
        "targetChangedShort": ["Focus changed", "输入位置已改变", "輸入位置已改變"],
        "polishEnabled": ["Polish text", "启用文字润色", "啟用文字潤飾"],
        "edit": ["Edit", "编辑", "編輯"],
        "undo": ["Undo", "撤销", "還原"],
        "cut": ["Cut", "剪切", "剪下"],
        "pasteAction": ["Paste", "粘贴", "貼上"],
        "selectAll": ["Select All", "全选", "全選"],
        "automatic": ["Automatic", "自动", "自動"],
        "recognitionLanguage": ["Recognition language", "识别语言", "辨識語言"],
        "chinesePreference": ["Chinese output", "中文输出偏好", "中文輸出偏好"],
        "chinese": ["Chinese", "中文", "中文"],
        "english": ["English", "英语", "英語"],
        "simplified": ["Simplified Chinese", "简体中文", "簡體中文"],
        "traditional": ["Traditional Chinese", "繁体中文", "繁體中文"],
        "changeShortcut": ["Change…", "修改…", "修改…"],
        "captureShortcut": ["Press a shortcut; release modifier-only keys. Esc cancels.", "请按快捷键；纯修饰键松开后确认。Esc 取消。", "請按快速鍵；純修飾鍵放開後確認。Esc 取消。"],
        "shortcutHint": ["Fn, Fn + Space, or a modifier + key. Avoid system shortcuts. ⌃⌥⌘S always opens settings.", "支持 Fn、Fn＋空格、修饰键＋按键。请避开系统快捷键。⌃⌥⌘S 始终用于打开设置。", "支援 Fn、Fn＋空白鍵、修飾鍵＋按鍵。請避開系統快速鍵。⌃⌥⌘S 固定用於開啟設定。"],
        "interaction": ["Recording gesture", "录音交互", "錄音操作"],
        "toggleFn": ["Press Fn to start / stop", "按一下 Fn 开始／结束", "按一下 Fn 開始／結束"],
        "holdFn": ["Hold Fn to talk", "按住 Fn 说话，松开提交", "按住 Fn 說話，放開提交"],
        "insertion": ["Insert text", "上屏方式", "輸入方式"],
        "paste": ["Paste from clipboard", "剪贴板自动粘贴", "剪貼簿自動貼上"],
        "typing": ["Type directly", "直接键入", "直接鍵入"],
        "copyOnly": ["Copy only", "仅复制", "僅複製"],
        "resume": ["Resume recognition", "继续识别", "繼續辨識"],
        "paused": ["Cancelled · recover within", "已取消 · 可恢复", "已取消 · 可恢復"],
        "inserting": ["Inserting…", "正在输入…", "正在輸入…"],
        "inserted": ["Text inserted", "已上屏", "已輸入"],
        "accessibility": ["Accessibility permission", "辅助功能权限", "輔助使用權限"],
        "inputMonitoring": ["Input Monitoring permission", "输入监控权限", "輸入監控權限"],
        "grant": ["Allow…", "授权…", "授權…"],
        "granted": ["Allowed", "已授权", "已授權"],
        "permissionHint": ["Fn and automatic insertion need permissions. After allowing access, click Refresh or reopen the app. Set the system Fn/Globe action to Do Nothing to avoid conflicts.", "Fn 和自动上屏需要权限。授权后点刷新或重启应用。建议将系统 Fn／地球键操作设为“不执行任何操作”，避免冲突。", "Fn 與自動輸入需要權限。授權後點重新整理或重啟 App。建議將系統 Fn／地球鍵設為「不執行任何動作」，避免衝突。"],
        "refresh": ["Refresh", "刷新", "重新整理"],
        "permissionsMissing": ["Allow Accessibility in Settings to use Fn.", "请在设置中授权辅助功能，以使用 Fn。", "請在設定中授權輔助使用，以使用 Fn。"],
        "targetChanged": ["Focus changed; insertion stopped. Your result is available to copy.", "输入位置改变，已停止写入。结果已保留，可点击复制。", "輸入位置改變，已停止寫入。結果已保留，可點擊複製。"],
        "insertionFailed": ["Automatic insertion is unavailable. Your result is available to copy.", "无法自动上屏。结果已保留，可点击复制。", "無法自動輸入。結果已保留，可點擊複製。"],
        "insertHint": ["Automatic paste temporarily uses the clipboard, then restores it unless you copied something new. Direct typing leaves it unchanged, including on failure. Copy only replaces it for manual pasting.", "自动粘贴会临时使用剪贴板，随后恢复原内容；期间若有新复制，则保留新内容。直接键入不改剪贴板，失败时也不自动复制。仅复制会覆盖剪贴板，由你自行粘贴。", "自動貼上會暫時使用剪貼簿，隨後還原原內容；期間若有新複製，則保留新內容。直接鍵入不改剪貼簿，失敗時也不自動複製。僅複製會覆蓋剪貼簿，由你自行貼上。"],
        "showDock": ["Show in Dock", "显示 Dock 图标", "顯示 Dock 圖示"],
        "showMenu": ["Show in menu bar", "显示菜单栏图标", "顯示選單列圖示"],
        "login": ["Launch at login", "登录时自动启动", "登入時自動啟動"],
        "loginApproval": ["Approve in System Settings", "在系统设置中允许", "在系統設定中允許"],
        "loginFailed": ["Could not update login item. Move the app to Applications and try again.", "无法更改启动项，请将应用移至应用程序文件夹后重试。", "無法變更啟動項目，請將 App 移至應用程式檔案夾後重試。"],
        "shortcut": ["Record / stop", "录音／停止", "錄音／停止"],
        "openSettings": ["Open settings", "打开设置", "開啟設定"],
        "backgroundHint": ["Close this window to keep running. ⌃⌥⌘S opens settings, even with both icons hidden.", "关闭窗口后仍在后台运行。即使隐藏全部图标，也可按 ⌃⌥⌘S 打开设置。", "關閉視窗後仍在背景執行。即使隱藏全部圖示，也可按 ⌃⌥⌘S 開啟設定。"],
        "hotkeyFailed": ["A shortcut is already in use. Quit the conflicting app and reopen YouJustSay.", "快捷键被占用，请退出冲突应用后重新打开你就说。", "快速鍵已被佔用，請結束衝突 App 後重新開啟你就說。"],
        "copiedHint": ["Copied. Paste wherever you need.", "已复制，可粘贴到任何地方。", "已複製，可貼上至任何地方。"],
        "utilityPrivacy": ["Stop to send audio to Doubao. When enabled, polishing sends text to your selected provider. The result is copied; no history is saved.", "停止后发送录音至豆包；启用润色时发送文字至所选整理服务商。结果按所选方式上屏，不保存历史。", "停止後傳送錄音至豆包；啟用潤飾時傳送文字至所選整理服務商。結果依所選方式輸入，不儲存歷史。"],
        "polishSwitch": ["Enable text polishing", "启用文字润色", "啟用文字潤飾"],
        "copyOriginal": ["Copy original", "复制识别原文", "複製辨識原文"],
        "retryPolish": ["Retry polishing", "重试润色", "重試潤飾"] ,
        "app": ["YouJustSay", "你就说", "你就說"],
        "tagline": ["Your voice, clearly written.", "说出想法，让表达更清晰。", "說出想法，讓表達更清晰。"],
        "workspace": ["Workspace", "工作台", "工作區"],
        "history": ["Recent notes", "最近记录", "最近記錄"],
        "new": ["New note", "新建记录", "新增記錄"],
        "untitled": ["Untitled note", "未命名记录", "未命名記錄"],
        "settings": ["Settings", "设置", "設定"],
        "language": ["Interface language", "界面语言", "介面語言"],
        "general": ["General", "通用", "一般"],
        "speech": ["Speech recognition", "语音识别", "語音辨識"],
        "doubao": ["Volcengine · Doubao Speech", "火山·豆包语音", "火山·豆包語音"],
        "organizer": ["Text cleanup", "文本整理", "文字整理"],
        "record": ["Start recording", "开始录音", "開始錄音"],
        "stop": ["Stop & transcribe", "停止并识别", "停止並辨識"],
        "ready": ["Ready when you are", "准备好了，尽管说", "準備好了，儘管說"],
        "recording": ["Listening…", "正在聆听…", "正在聆聽…"],
        "transcribing": ["Transcribing…", "正在识别…", "正在辨識…"],
        "polishing": ["Organizing…", "正在整理…", "正在整理…"],
        "requesting": ["Requesting microphone…", "正在请求麦克风…", "正在請求麥克風…"],
        "original": ["Original", "原始文字", "原始文字"],
        "result": ["Organized", "整理结果", "整理結果"],
        "placeholder": ["Record a thought, or type and paste here.", "录下想法，也可以在这里输入或粘贴文字。", "錄下想法，也可以在這裡輸入或貼上文字。"],
        "resultHint": ["A clearer version of your words will appear here.", "整理后的文字会显示在这里。", "整理後的文字會顯示在這裡。"],
        "organize": ["Organize text", "整理文字", "整理文字"],
        "copy": ["Copy", "复制", "複製"],
        "copied": ["Copied", "已复制", "已複製"],
        "cancel": ["Cancel", "取消", "取消"],
        "retry": ["Retry transcription", "重试识别", "重試辨識"],
        "delete": ["Delete note", "删除记录", "刪除記錄"],
        "deleteQuestion": ["Delete this note?", "删除这条记录？", "刪除此記錄？"],
        "deleteDetail": ["Its original and organized text will be removed from this Mac.", "原始文字与整理结果将从此 Mac 中删除。", "原始文字與整理結果將從此 Mac 中刪除。"],
        "style": ["Cleanup style", "整理风格", "整理風格"],
        "clean": ["Light polish", "轻度润色", "輕度潤飾"],
        "bullets": ["Key points", "提炼要点", "提煉重點"],
        "email": ["Email", "邮件草稿", "郵件草稿"],
        "auto": ["Organize after transcription", "识别后自动整理", "辨識後自動整理"],
        "save": ["Save credentials", "保存凭据", "儲存憑證"],
        "saved": ["Keys saved on this Mac", "密钥已安全保存在本机", "金鑰已安全儲存在本機"],
        "keyHint": ["API keys connect to your services and are stored in macOS Keychain. Save after editing; clearing a field and saving removes its key. Other settings save automatically.", "API 密钥用于连接服务，保存在 macOS 钥匙串中。修改后请保存；清空字段并保存可删除对应密钥。其他设置自动保存。", "API 金鑰用於連接服務，儲存在 macOS 鑰匙圈中。修改後請儲存；清空欄位並儲存可刪除對應金鑰。其他設定自動儲存。"],
        "apiKey": ["API key", "API 密钥", "API 金鑰"],
        "auth": ["Credential type", "密钥类型", "金鑰類型"],
        "modern": ["API key (recommended)", "API 密钥（推荐）", "API 金鑰（建議）"],
        "legacy": ["App ID + Access token", "旧版 App ID + Access Token", "舊版 App ID + Access Token"],
        "model": ["Model", "模型", "模型"],
        "setup": ["Set up providers to start", "配置服务商后即可开始", "設定服務商後即可開始"],
        "limit": ["Up to 5 minutes per recording · ⌘⇧R to record", "单次录音最长 5 分钟 · ⌘⇧R 录音", "單次錄音最長 5 分鐘 · ⌘⇧R 錄音"],
        "micDenied": ["Allow microphone access in System Settings → Privacy & Security → Microphone.", "请在系统设置 → 隐私与安全性 → 麦克风中允许访问。", "請在系統設定 → 隱私權與安全性 → 麥克風中允許存取。"],
        "micFailed": ["Unable to start recording. Check your microphone.", "无法开始录音，请检查麦克风。", "無法開始錄音，請檢查麥克風。"],
        "missingSpeech": ["Set up Doubao Speech first.", "请先配置火山·豆包语音", "請先設定火山·豆包語音"],
        "missingLLM": ["Set up your text provider.", "请先配置文字整理服务", "請先設定文字整理服務"],
        "empty": ["No speech or text was returned. Please try again.", "未返回语音或文字内容，请重试。", "未傳回語音或文字內容，請重試。"],
        "response": ["The provider returned an invalid response.", "服务商返回了无效响应。", "服務商傳回了無效回應。"],
        "truncated": ["The output was cut short. Try a shorter input.", "输出被截断，请缩短原文后重试。", "輸出遭截斷，請縮短原文後重試。"],
        "network": ["Connection failed. Check your network and try again.", "连接失败，请检查网络后重试。", "連線失敗，請檢查網路後重試。"],
        "storage": ["Could not save notes on this Mac.", "无法在本机保存记录。", "無法在本機儲存記錄。"],
        "keychain": ["Could not access macOS Keychain.", "无法访问 macOS 钥匙串。", "無法存取 macOS 鑰匙圈。"],
        "serviceError": ["Provider error", "服务商错误", "服務商錯誤"],
        "error": ["Something needs attention", "需要处理的问题", "需要處理的問題"],
        "close": ["Dismiss", "关闭", "關閉"],
        "emptyHistory": ["Your ideas start here", "从一个想法开始", "從一個想法開始"],
        "docs": ["Provider documentation", "服务商文档", "服務商文件"],
        "speechHint": ["Enable the flash transcription service (volc.bigasr.auc_turbo) in the Doubao console.", "请在豆包控制台开通录音文件极速版服务（volc.bigasr.auc_turbo）。", "請在豆包控制台開通錄音檔案極速版服務（volc.bigasr.auc_turbo）。"],
        "quitRecording": ["Recording is active. Quit anyway?", "正在录音，仍要退出吗？", "正在錄音，仍要結束嗎？"],
        "quit": ["Quit", "退出", "結束"]
    ]
}

enum WritingStyle: String, Codable, CaseIterable, Identifiable {
    case basic, clean, structured
    var id: String { rawValue }
    var instruction: String {
        switch self {
        case .basic: "Perform basic cleanup only: remove clearly meaningless speech fillers and accidental stutters, and correct necessary punctuation. Keep the original words, word order, grammar, tone and paragraph form. Do not paraphrase, polish vocabulary, restructure, add headings or make lists. When uncertain whether a word carries meaning, keep it."
        case .clean: "Lightly polish the transcript: remove fillers and accidental repetition, correct punctuation and grammar. Preserve the original wording, order, tone and paragraph form wherever possible. Do not add headings or lists unless already present."
        case .structured: "Restructure the transcript by topic into clear sections, concise headings and organized lists where useful. Group related points and clarify their relationships while retaining all substantive details, uncertainty and qualifications. Scale the structure to the content; do not force headings for a short sentence. Never invent facts, conclusions, action items or commitments."
        }
    }
}
